#!/bin/tcsh
# Job name: AMBER_CUDA_JOB
#SBATCH --job-name=rapa_test 
#
# Account:
#SBATCH --account=pgera
#
# Partition:
#SBATCH --partition=hpc
#
# Number of nodes:
#SBATCH --nodes=1
#
# Number of tasks (one for each GPU desired for use case) (example):
#SBATCH --ntasks=1
#
# Processors per task (please always specify the total number of processors as twice the number of GPUs):
#SBATCH --cpus-per-task=1
#
#Number of GPUs, this can be in the format of "gpu:[1-4]", or "gpu:K80:[1-4] with the type included
#SBATCH --gres=gpu:1
#
# Wall clock limit:
##SBATCH --time=00:00:30
#
## Command(s) to run -- Put your AMBER comannds below -- A sample pmemd.cuda command is shown below -- Replace this with your own
## $1 is the rest file
## $2 is the topology file
## $3 is the corrdinate file
## $4 is the root name for the output files





rapa.py -pID $1 -HLPsp2_known $2 -o $3 

